### ISSUE TITLE
Matcher creation function name

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#17]
In core, we have `NewCoreMatcher()` but in Pruner we have `pruner.NewMatcher()`.  These should be consistent with each other.

**Comment by embano1** [comment]
Sounds like `<pkg>.NewMatcher` would be consistent and avoid the pkg name in the function?

**Comment by timbray** [comment]
So there are two things: The name of the type that implements `Matcher` interface and the name of the function to create one.  

Quamina already defines the Matcher interface so for core we're stuck with `CoreMatcher` unless we move the definition of `Matcher` interface to somewhere else.

**Comment by embano1** [comment]
IMHO this is due to some package and type naming.

For example, `core` is a pretty big package doing a lot, compared to making it about the behavior (e.g. `package matcher`) which is more Go idiomatic if you want.

Since we won't change the package structure now, we could rename `CoreMatcher` to `DefaultMatcher` and instantiate it with `core.NewMatcher()` which would give you the "default"/ready to use struct.

Thoughts?

**Comment by jsmorph** [comment]
Also see #34, which discusses packages.

**Comment by timbray** [comment]
> Since we won't change the package structure now, we could rename `CoreMatcher` to `DefaultMatcher` and instantiate it with `core.NewMatcher()` which would give you the "default"/ready to use struct.

Why not change the package structure?  I'm not convinced that the current structure is optimal.

**Comment by embano1** [comment]
> Why not change the package structure? I'm not convinced that the current structure is optimal.

Be my guest! Wasn't sure if I can (should) put more on your shoulders :)

**Comment by timbray** [comment]
Obsoleted by 47e219e2d8a71342783f8a7ee18ef9aa92cd490f
